### ISSUE TITLE
Fix still not working

### ISSUE THREAD

**Issue by Timmiller109** [Ar1i/PokemonGo-Bot#1110]
With the new fix, it is still not working. Its unable to load the pokemon list as well as restarting quite frequently.
![screenshot_1](https://cloud.githubusercontent.com/assets/20779663/17369738/0f51b1d4-595f-11e6-8a86-f4f4f640898d.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/20779663/17369743/116d1562-595f-11e6-9efa-530e46a364bd.png)

**Comment by Ar1i** [comment]
Cause you probably didnt got the images from the server, adding a timeout to the webclient.. gimme about 10min~

**Comment by Timmiller109** [comment]
thank you for the fast reply and the amazing work. you are awesome.

**Comment by Praxthisnovcht** [comment]
sorry to disturb your conversation.
but where is located your GPS to find canine

**Comment by Ar1i** [comment]
should be fixed

**Comment by Timmiller109** [comment]
i found most of those at santa monica pier in california, usa 
34.0093515
-118.49746820000001

**Comment by Timmiller109** [comment]
Ar1i, it still isnt working and i got a new error. 
![screenshot_1](https://cloud.githubusercontent.com/assets/20779663/17371213/afd0a52a-5964-11e6-9700-d7d89c431bbf.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/20779663/17371218/b14f49a6-5964-11e6-805c-295cac84ec30.png)
![screenshot_3](https://cloud.githubusercontent.com/assets/20779663/17371221/b28431a6-5964-11e6-9cc9-b1701e3afa63.png)
