### ISSUE TITLE
So, this is my issue

### ISSUE THREAD

**Issue by kizziace** [Ar1i/PokemonGo-Bot#2191]
I have no idea whats going on
![error](https://cloud.githubusercontent.com/assets/20894205/17500824/0799e65e-5d8e-11e6-9d2f-1242f239303a.png)

**Comment by xJustx** [comment]
Do you have the newest version?

**Comment by Midnlght** [comment]
it usually fixes it self for me , you can try restarting the bot or like @xJustx  said try to download the newest version if you haven't yet mate @kizziace

**Comment by navygino** [comment]
This issue I solved by:
1,) Delete everything in the Config folder.
2.) Run as admin

**Comment by kizziace** [comment]
yes I have the latest version, and yes deleted everything in the config folder, which that solved the gui problem so that can load but I'm still getting all the grey lines coming up

**Comment by kizziace** [comment]
I even tried deleting the whole folder, and extracting it again and running as admin, I'm still having that issue

**Comment by kizziace** [comment]
I got it working thankfully, not quite sure what I did but it was a mix of restarting my laptop and deleting the config and running as admin, and only running two at a time instead of 4 ( I do I have 3 and I help a friend)

**Comment by xJustx** [comment]
^
