### ISSUE TITLE
Something wrong with the funtion "Break at lure"

### ISSUE THREAD

**Issue by Siufay1** [Ar1i/PokemonGo-Bot#3581]
I found a place with 4 pokestops nearby. The bot just stood there for 28 mins keeping farming 4 pokestops without catching pokemons.

**Comment by Kidnub** [comment]
check your options ?= if farming is on in the gui ;(

**Comment by MTK4355** [comment]
I was just using it and catching Pokémon, so I think the logic around catching still works. Did the bot not resume walking when the lure expired?

**Comment by MTK4355** [comment]
My problem was that the area I was in had a bunch of lures, but they were not overlapping so I was pausing at a single stop for 15-20 minutes, then I'd move to the next and wait there for another 15-20 and so on; potentially missing all of the pokemon at the other active lures in the area. 

Starting to think the feature might not be very useful in it's current form, but not quite sure what direction to take it. 

Any ideas?

**Comment by Kidnub** [comment]
At the moment i search some lures but i could test it with my last troydisk cause my account in the bot is just a test account XD just to see how fast they do ban ... in the moment i can say lol 14days (cause i used even the offline version of the bot) no ban . XD 
and i had never any problem to catch any pokemon at any lure ... i didn miss any much ..(but i ll test it with a video cause iam to lazy to watch all time XD on it so give me 1 hour with recording and uploading XD

**Comment by MTK4355** [comment]
I broke it trying to fix the issue where the pokestops don't show up unless you open the map right away. doh! I'll get it right soon.

**Comment by Kidnub** [comment]
Yes XD

**Comment by Kidnub** [comment]
at the moment i can only say  the bot catch the pokemons but the spawn rate at lure is down

**Comment by Logxn** [comment]
fixed

**Comment by Andrewaj** [comment]
it seems like when "use Lure at break enabled" is still not catching pokemons. Its stopping and farming pokestop, but no logs suggesting that any of pokemons was catch. 
![image](https://cloud.githubusercontent.com/assets/22095072/18381822/fd3ef46e-7675-11e6-8d0f-132b7aedcaac.png)
