### ISSUE TITLE
Pokelist Problem(error microsoft 403)

### ISSUE THREAD

**Issue by hendek95** [Ar1i/PokemonGo-Bot#760]
After last update getting this code. i search but i couldn't fix it. solve for error code=https://support.microsoft.com/en-us/kb/837727
but i wanted hotfix to my email. after i started setup "an unexpected internal error has accured." i can't solve these problems dont have enough information. But i guess it s about server and our connection. 
![error](https://cloud.githubusercontent.com/assets/20742246/17303382/20d14492-5829-11e6-8d44-b737fe5bca9c.png)

**Comment by Tochez** [comment]
This  is due to ur system not the bot @hendek95

**Comment by hendek95** [comment]
i know problem is belong to pc or connection. but many people have that problem.

**Comment by JustPlaysDE** [comment]
fixed

**Comment by hendek95** [comment]
not fixed :(
![ar1i](https://cloud.githubusercontent.com/assets/20742246/17336253/fdcc0b0e-58e5-11e6-8cf8-bcbd120407df.png)

**Comment by hendek95** [comment]
Fixed for ar1i s bot! pls read this error = https://social.msdn.microsoft.com/Forums/sqlserver/en-US/ef0f1c39-fc92-4cde-9920-597a8d6981f9/403-error-the-remote-server-returned-an-error-403-forbidden?forum=sqlreportingservices
